spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  datasource:
    url: jdbc:postgresql://localhost:5432/tidarobot
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
jwt:
  secret: ${JWT_SECRET}
encryption:
  secret: ${ENCRYPTION_KEY}
parking:
  trigger-hour: 16
  python-executable: python3
  python-script-path: src/main/resources/login.py